### ISSUE TITLE
Reclaiming the Ruins quest can not be completed

### ISSUE THREAD

**Issue by SamoyedProtW** [YggdrasilWotLK/Yggdrasil-WoW#75] opened 2024-08-16 18:20 UTC
Quest finisher NPC does not accept finished quest. Bug also has been observed by GM Zeleot

**Comment by YggdrasilWotLK** [comment] 2024-08-19 19:07
Can't reproduce, please elaborate on reproduction steps @SamoyedProtW

**Comment by YggdrasilWotLK** [comment] 2024-09-23 16:30
Closing for now as we can't reproduce and author not supplying further information

**Closed as completed by YggdrasilWotLK** 2024-09-23 16:30 UTC
Labels: More information needed
