### ISSUE TITLE
Quest: Convocation at Zol'heb (ID: 12730)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#51] opened 2024-07-23 12:01 UTC
Quest: Convocation at Zol'heb (ID: 12730)

This quest includes taking a quest item and using the ritual thing at the altar or whatever the green rune thing is on the ground. All of which is normally functional, upon engaging the quest boss - This guy at some point should cast a blast wave like spell (similar tooltip) and just then cause you to become stunned and immobile while the same thing happens to him as well. You both stay stunned for a moment or so and Harkoa should show up to help and basically murder the guy while Har koa will dispell the debuff on you to help you stay alive and all too. None of the roleplay after the explode and stun works or happens, and you remain indefinitely stuck there able to do nothing at all. 

https://www.youtube.com/watch?v=97j-wwK_soU&ab_channel=DibuckTV

**Comment by Lortz92** [comment] 2024-07-24 15:20
This bug you reported happened to me 2 times out of 8. What was missing since the beginning was the kill credit after you slay Prophet of Akali and i fixed this one. Now i need to understand why sometimes it bugs out.

**Comment by Lortz92** [comment] 2024-07-28 16:33
We found out why roleplay didn't work sometimes. Was caused by not being in the area that triggers roleplay, so i solved by tele him in and that did the trick for now.

**Comment by YggdrasilWotLK** [comment] 2024-08-11 18:36
@Lortz92  could you please have a look another look at this? Not working on prod

**Comment by Lortz92** [comment] 2024-08-12 12:49
I've added a new event to fix this, basically the issue was if you were too close to him, he would run towards you even if you told him to stop autoattack and the roleplay didn't trigger. I made him stay still to trigger roleplay after no autoattack

**Comment by Ye-Old-Potato** [comment] 2024-08-15 06:37
This looks about right at least on the QA it works pretty much as we'd gotten it to, even smoother now the sense of the roleplay and overall look.

**Comment by YggdrasilWotLK** [comment] 2024-10-25 12:19
@Lortz92 https://github.com/YggdrasilWotLK/Yggdrasil-WoW/issues/112 seems there's still issues

**Comment by Lortz92** [comment] 2024-10-25 17:11
I don't know how to replicate this. I saw another issue with detectionrange of dude that would end in resets his hp and set his immunity flag back. Fixed this thing but i still don't know what caused the issue...I tried several times and was working always.

**Comment by YggdrasilWotLK** [comment] 2024-11-01 05:49
New adjustment is now live, closing as we can't find any more issues with the quest on dev

**Closed as completed by YggdrasilWotLK** 2024-11-01 05:49 UTC
Labels: DB, Ready to go live
