### ISSUE TITLE
Quest: Leave no one behind (QID: 12512)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#79] opened 2024-08-18 06:33 UTC
Quest: Leave no one behind (QID: 12512)

 The bandages should revive the crusaders and then you should be able to walk them back to the camp and submit each of them within a timer. Everything here works except the part where you submit each crusader. So when you take the crusader to the submit area, they don't get submitted - I couldn't see that "GM mode infernal" standing there either which usually signifies such a script. Of note, this doesn't always happen in the first attempt but rather if 1 player just did it, the next player can't do it or something like that seems to be the issue. So maybe do it 2-3 times repeatedly to try and replicate the issue.

https://www.youtube.com/watch?v=dBFQKwmaBQg

(Doesn't show the submitting part, couldn't find a video that did, but yeah - it's quite straightforward. It's just that the "Bringing of the crusader to the submission point, does not register that the crusader is saved, NOT the actual "submission" of the quest, if you force .quest complete, then it can be done).

**Comment by YggdrasilWotLK** [comment] 2024-08-19 19:33
Duplicate of https://github.com/YggdrasilWotLK/Yggdrasil-WoW/issues/67, please check existing issues before creating new ones

**Closed as completed by YggdrasilWotLK** 2024-08-19 19:33 UTC
Labels: Duplicate
