### ISSUE TITLE
Quest: The Fate of Bloodbane (QID: 13164)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#77] opened 2024-08-18 06:24 UTC
Quest: The Fate of Bloodbane (QID: 13164)

Dude doesn't like to spawn, check the IDs below for the guy who is supposed to spawn. 
(29204/31283 <-- Likely NPC ID for that specific spot)

Intended working: He should just be there and spawned pretty much like a normal world mob, elite, but similar.

Note: Potentially spawns some times or has either a wonky, or a a misaligned spawn timer, or is just generally invisible for some strange reasons since the NPC location does teleport you to where he should be (i.e. the .go command), but nothing is there when you go there.

**Comment by YggdrasilWotLK** [comment] 2024-08-19 19:49
Nothing wrong here, he's there on prod, dev and QA. His respawn timer is 10 minutes (or, rather, his corpse stays for 5 minutes and after it despawns he has a 5-minute timer to respawning). So I'm assuming you or whoever made this report tried to find him within those 10 minutes?

![image](https://github.com/user-attachments/assets/947468d3-fbe5-4508-9b89-1be7ef16a86b)


Side note: the .go creature command teleports you to his _spawn point_, not necessarily where he is now or where his corpse is

**Comment by YggdrasilWotLK** [comment] 2024-08-20 11:51
Closing as can't reproduce, will reopen if issue happens again

**Closed as completed by YggdrasilWotLK** 2024-08-20 11:51 UTC
Labels: More information needed
